name: hyper-task-manager

services:
  mongodb:
    image: mongo:6.0.8
    container_name: hyper-mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - 27017:27017
    env_file:
      - .env
    networks:
      - hyper-task-manager-network
    volumes:
      - mongo-data:/data/db

  hyper-service:
    image: mayarun/hyper-composer:latest
    container_name: hyper-task-manager
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_HOST_NAME: ${MONGO_HOST_NAME}
      MONGO_PORT_NUMBER: ${MONGO_PORT_NUMBER}
    env_file:
      - .env

volumes:
  mongo-data:

networks:
  hyper-task-manager-network:
